// <auto-generated />
using System;
using Biblioteca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity<Emprestimo>(entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                entity.Property<DateTime?>("DataDevolucao")
                    .HasColumnType("datetime(6)");

                entity.Property<DateTime>("DataEmprestimo")
                    .HasColumnType("datetime(6)");

                entity.Property<bool>("Devolvido")
                    .HasColumnType("tinyint(1)");

                entity.Property<string>("Estado")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.Property<int>("LivroId")
                    .HasColumnType("int");

                entity.Property<string>("NomeUsuario")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.Property<string>("Telefone")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.HasKey("Id");

                entity.HasIndex("LivroId");

                entity.ToTable("Emprestimos", (string)null);
            });

            modelBuilder.Entity<Livro>(entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                entity.Property<int>("Ano")
                    .HasColumnType("int");

                entity.Property<string>("Autor")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.Property<string>("Titulo")
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.HasKey("Id");

                entity.ToTable("Livros", (string)null);
            });

            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                entity.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("longtext CHARACTER SET utf8mb4");

                entity.HasKey("Id");

                entity.ToTable("Usuarios", (string)null);
            });

            modelBuilder.Entity<Emprestimo>(entity =>
            {
                entity.HasOne<Livro>("Livro")
                    .WithMany()
                    .HasForeignKey("LivroId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}